# Generated by Django 3.2.10 on 2023-03-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
